"""initial

Revision ID: 05e4b8fa3628
Revises: 812921a011a1
Create Date: 2022-11-24 14:38:04.769881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e4b8fa3628'
down_revision = '812921a011a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.VARCHAR(length=100), nullable=True))
    op.add_column('items', sa.Column('category_id', sa.VARCHAR(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category_id')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
