"""initial

Revision ID: 68fc5299791f
Revises: ac34a80a1308
Create Date: 2022-11-22 18:58:47.627400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fc5299791f'
down_revision = 'ac34a80a1308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
