"""initial

Revision ID: 812921a011a1
Revises: 68fc5299791f
Create Date: 2022-11-24 14:27:41.986602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812921a011a1'
down_revision = '68fc5299791f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('items', 'category_name')
    op.drop_column('items', 'price')
    op.drop_column('items', 'category_code')
    op.drop_column('items', 'subcategori_code')
    op.drop_column('items', 'subcategori_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('subcategori_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('subcategori_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('category_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('category_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('categories')
    # ### end Alembic commands ###
