"""initial

Revision ID: 9f5aa5fc2178
Revises: b8090150a3a0
Create Date: 2022-11-22 18:50:58.262786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5aa5fc2178'
down_revision = 'b8090150a3a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategori_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('subcategori_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
